### ISSUE TITLE
Custom transformer

### ISSUE THREAD

**Issue by Sammi89** [ambassify/parse-js#56]
Hi, first I wanted to thank you for this fantastic library.
I want to know if there is a way to create a transformer with custom logic.
Can anyone help me with this?
Thank you in advance.

**Comment by Sitebase** [comment]
Hi @Sammi89, sorry for the late reply. Hopefully, you've already found the solution to your question.
This can be accomplished by using [chain](https://github.com/ambassify/parse-js#chain).
